config/routes.rb
Rails.application.routes.draw do
  resources :activities
  root to: "landing#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
    has_many :laps
    has_many :lap_summaries, through: :laps

    has_attached_file :gpx
    validates_attachment_file_name :gpx, :matches => [/gpx\Z/, /xml\Z/]
    before_save :parse_file

    def parse_file
        tempfile = gpx.queued_for_write[:original]
        doc = Nokogiri::XML(tempfile)
        parse_xml(doc)
    end 

    private

    def parse_xml(doc)
        doc.root.elements.each do |node|
            parse_activities(node) if node.node_name.eql? "Activities"    
        end
    end

    def parse_activities(activities)
        activities.elements.each do |node|
            parse_activity(node) if node.node_name.eql? "Activity"   
        end 
    end

    def parse_activity(activity)
        self.sport = activity.attr('Sport')
        activity.elements.each do |node|
            parse_activity_id(node) if node.node_name.eql? "Id"
            self.laps << parse_lap(node) if node.node_name.eql? "Lap"
        end
    end    

    def parse_activity_id(activity_id)
        self.activity_id = DateTime.parse(activity_id.text.to_s)
    end

    def parse_lap(lap)
        lap_summary = parse_lap_summary(lap)
        Lap.new(
            start_time: parse_lap_start_time(lap.attr('StartTime')),
            lap_summary: lap_summary
        )
    end

    def parse_lap_summary(lap)
        lap_summary = LapSummary.new
        lap.elements.each do |node|
            lap_summary.total_time_seconds = node.text.to_f if node.node_name.eql? "TotalTimeSeconds"
            lap_summary.distance_meters = node.text.to_f if node.node_name.eql? "DistanceMeters"
            lap_summary.maximum_speed = node.text.to_f if node.node_name.eql? "MaximumSpeed"
            lap_summary.calories = node.text.to_f if node.node_name.eql? "Calories"
            lap_summary.average_heart_rate_bmp = node.elements.first.text.to_i if node.node_name.eql? "AverageHeartRateBmp"
            lap_summary.maximum_heart_rate_bmp = node.elements.first.text.to_i if node.node_name.eql? "MaximumHeartRateBmp"
            lap_summary.intensity = node.text.to_s if node.node_name.eql? "Intensity"
            lap_summary.cadence = node.text.to_i if node.node_name.eql? "Cadence"
            lap_summary.trigger_method = node.text.to_s if node.node_name.eql? "TriggerMethod"
        end
        lap_summary
    end

    def parse_lap_start_time(start_time_data)
        DateTime.parse(start_time_data)
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lap.rb
class Lap < ApplicationRecord
  belongs_to :activity
  has_one :lap_summary
end

app/models/lap_summary.rb
class LapSummary < ApplicationRecord
  belongs_to :lap
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    def index
        @activities = Activity.all  
    end

    def new
        @activity = Activity.new
    end

    def create
        activity = Activity.new(activity_params)
        if activity.save
            redirect_to action: "index", notice: "Poprawnie dodano nowy trening!"
        else
            redirect_to action: "new"
        end
    end

    def show 
        @activity = Activity.find(params[:id])
    end

    private
    def activity_params
        params.require(:activity).permit(:name, :gpx)    
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
    def index
    end
end

app/controllers/lap_summaries_controller.rb
class LapSummariesController < ApplicationController
end

app/controllers/laps_controller.rb
class LapsController < ApplicationController
end

app/helpers/acitivities_helper.rb
module AcitivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lap_summaries_helper.rb
module LapSummariesHelper
end

app/helpers/laps_helper.rb
module LapsHelper
end

app/views/activities/_form.html.erb
<%= form_for @activity, html: { class: 'form-horizontal' } do |f| %>
<div class="control-group">
    <div class="controls">
      <%= f.text_field :name, :class => 'main-curved', :placeholder => '  training name' %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <div class="file-input-wrapper">
        <%= f.button "  .ctx training file", :class => 'main-button-file-upload main-curved' %>
        <%= f.file_field :gpx,  :class => 'main-file-upload' %>
      </div>
    </div>
  </div>
  <div class="centered_div">
    <%= f.submit "Submit", :class => 'btn btn-submit btn-margin' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                activities_path, :class => 'btn btn-primary btn-margin' %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/activities/index.html.erb
<div class="main-header">
  <%= image_tag("unnamed.png", class: "main-logo")%>
</div>

<div class="main-background index-background">
  <div class="main-title index-title">
    <%=t '.title', default: "Tell us about your training" %>
  </div>

  <div class = "centered_div">
    <%= link_to t('.new', default: "add new training"),
              new_activity_path,
              class: 'btn btn-primary btn-index-main btn-margin' %>
  </div>
</div>

<div class="main-title small-title centered_div">
  <%=t '.title', default: "What you achieved recently" %>
</div>

<%- model_class = Activity -%>
<div class="training_container">
<table class="main-table">
  <tbody>
    <% @activities.each do |activity| %>
      <tr class="main-table">
        <td class="main-table trainings_table"><%= activity.id %></td>
        <td class="main-table trainings_table"><%= activity.name %></td>
        <td class="main-table trainings_table"><%= activity.sport %></td>
        <td class="main-table trainings_table"><%= activity.laps.count %> laps</td>
        <td class="main-table trainings_table">
          <%= link_to activity_path(activity), class: 'details-btn', title: "Details" do %>
              details
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/activities/new.html.erb
<div class="main-header">
  <%= image_tag("unnamed.png", class: "main-logo")%>
</div>

<div class="main-background new-activity-background">
  <%- model_class = Activity -%>
  <div class="main-title">
    <%=t '.title', default: "Add new training", model: model_class.model_name.human.titleize %>
  </div>
  <div class="main-container">

      <%= render partial: 'form' %>

  </div>
</div>

app/views/activities/show.html.erb
<div class="main-header">
  <%= image_tag("unnamed.png", class: "main-logo")%>
</div>


<%- model_class = Activity -%>

<div class="training_container training_info">
  <div class="training-title">
    <%=t '.title', default: @activity.name, model: model_class.model_name.human.titleize %>
    <div class="main-title sport-title">
      <%=t '.title', default: @activity.sport, model: model_class.model_name.human.titleize %>
    </div>
  </div>
</div>

<div class="main-title laps-title centered_div">
  <%=t '.title', default: "Laps" %>
</div>

        <table class="main-table">
          <thead>
            <tr class="main-table">
              <th class="main-table header_table">Id</th>
              <th class="main-table header_table">Start time</th>
              <th class="main-table header_table">Total time (in seconds)</th>
              <th class="main-table header_table">Distance (in meters)</th>
              <th class="main-table header_table">Maximum speed</th>
              <th class="main-table header_table">Intensity</th>
            </tr>
          </thead>
          <tbody>
            <% @activity.laps.each do |lap| %>
              <tr class="main-table">
                <td class="main-table training_table"><%= lap.id %></td>
                <td class="main-table training_table"><%= lap.start_time %></td>
                <td class="main-table training_table"><%= lap.lap_summary.total_time_seconds %></td>
                <td class="main-table training_table"><%= lap.lap_summary.distance_meters %></td>
                <td class="main-table training_table"><%= lap.lap_summary.maximum_speed %></td>
                <td class="main-table training_table"><%= lap.lap_summary.intensity %></td>
              </tr>
            <% end %>
          </tbody>
        </table>


<%#<div class="form-group">%>
<div class="centered_div">
  <%= link_to t('.back', default: t("helpers.links.back")),
              activities_path, class: 'btn btn-default btn-training'  %>
  <%#<%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_activity_path(@activity), class: 'btn btn-default' %>
  <%#<%= link_to t('.destroy', default: t("helpers.links.destroy")),%>
              <%#activity_path(@activity),%>
              <%#method: 'delete',%>
              <%#data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },%>
              <%#class: 'btn btn-danger' %>
</div>

app/views/landing/index.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <%= image_tag("unnamed.png", class: "landing-logo")%>
            <%= link_to "just ride BETTER.", { :controller => :activities, :action => :index }, { class: "btn btn-primary btn-xl" } %>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insight</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>